// <auto-generated />
using EFconASPyMVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFconASPyMVC.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240214153329_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFconASPyMVC.Models.CentroDeportivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CentrosDeportivos");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.CentroDeportivoUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CentroDeportivoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "CentroDeportivoId");

                    b.HasIndex("CentroDeportivoId");

                    b.ToTable("CentrosUsuarios");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroDeportivoId")
                        .HasColumnType("int");

                    b.Property<int>("Empleados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentroDeportivoId")
                        .IsUnique();

                    b.ToTable("Directores");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Pista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aforo")
                        .HasColumnType("int");

                    b.Property<int>("CentroDeportivoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentroDeportivoId");

                    b.ToTable("Pistas");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PistaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.CentroDeportivoUsuario", b =>
                {
                    b.HasOne("EFconASPyMVC.Models.CentroDeportivo", "CentroDeportivo")
                        .WithMany("CentroDeportivoUsuarios")
                        .HasForeignKey("CentroDeportivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFconASPyMVC.Models.Usuario", "Usuario")
                        .WithMany("CentroDeportivoUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroDeportivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Director", b =>
                {
                    b.HasOne("EFconASPyMVC.Models.CentroDeportivo", "CentroDeportivo")
                        .WithOne("Director")
                        .HasForeignKey("EFconASPyMVC.Models.Director", "CentroDeportivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroDeportivo");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Pista", b =>
                {
                    b.HasOne("EFconASPyMVC.Models.CentroDeportivo", null)
                        .WithMany("Pistas")
                        .HasForeignKey("CentroDeportivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFconASPyMVC.Models.CentroDeportivo", b =>
                {
                    b.Navigation("CentroDeportivoUsuarios");

                    b.Navigation("Director")
                        .IsRequired();

                    b.Navigation("Pistas");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Usuario", b =>
                {
                    b.Navigation("CentroDeportivoUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
